POST http://localhost:3000/api/grade
Content-Type: application/json

{
    "value":"5"
}

###
GET http://localhost:3000/api/grade

### 
DELETE  http://localhost:3000/api/grade/8


###
PUT   http://localhost:3000/api/grade
Content-Type: application/json

{
    "id":"5",
    "value":"5"
}


