POST http://localhost:3000/api/wilder
Content-Type: application/json

{
    "name":"tata"
}

###
GET http://localhost:3000/api/wilder

### 
DELETE  http://localhost:3000/api/wilder/1


###
PUT   http://localhost:3000/api/wilder
Content-Type: application/json

{
    "id":"3",
    "name":"tutu"
}


###
PUT http://localhost:3000/api/wilder/addskill
Content-Type: application/json

{
    "wilderName":"tutu",
    "skillName":"PHP"
}